### ISSUE TITLE
Move the contents within the runner config to the input dir config

### ISSUE THREAD

**Issue by yaseminbridges** [monarch-initiative/pheval.exomiser#23]
After working with the config in the `input-dir` to write the `application.properties`, which is already configured prior to the run, I agree that it makes sense to move any tool-specific configurations, that are needed to be referenced in the runner, into this file under a `tool_specific_configurations` field. 

Currently, the input-dir config looks like so:

```
tool: exomiser
tool_version: 13.2.0
phenotype_only: True
tool_specific_configuration_options:
```

However, I would like to propose that there are two additional fields added:

```
tool: exomiser
tool_version: 13.2.0
phenotype_only: True
post_processing:
    score_name: combinedScore
    sort_order: DESCENDING    # or can be ASCENDING
tool_specific_configuration_options:
```

This is particularly for tools that output several different scores and perhaps want to specify on which score you want to benchmark. The score order is required for the post-processing, i.e., if the best score is considered those with the lowest value (p-value) these will be ranked first in ascending order, or if the larger values are the best scores, then ranked in descending order. This can be added to the `tool_specific_configuration_options` field, however, it is information required currently in the post-processing methods so would propose that these are in the main part of the config.

Alternatively, if the tool only outputs a single score, like Phen2Gene they can choose to ignore these fields and just pass the arguments for the post-processing in the runner implementation.

@matentzn what do you think?
